language: php
php: 7.3
cache:
    directories: $HOME/.composer/cache
before_script: 
    - rm /home/travis/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini
    - composer install --no-interaction --dev
script:
    - composer run test
after_success: bash <(curl -s https://codecov.io/bash)
