language: php
php: 7.3
cache:
    directories: $HOME/.composer/cache
before_script: 
    - export XDEBUG_MODE=coverage
    - composer install --no-interaction --dev
script:
    - composer run test
    - test -f coverage.xml
after_success: bash <(curl -s https://codecov.io/bash)
